import type { Product } from "./types"

export const products: Product[] = [
  // Batteries
  {
    id: "b1",
    name: "Car Battery 65Ah",
    description: "Reliable 12V car battery suitable for most sedans",
    price: 350000,
    category: "Batteries",
    condition: "Brand New",
    image: "/laptop-battery.png",
    images: ["/laptop-battery.png", "/placeholder.svg", "/placeholder.svg"],
    brand: "Generic",
    inStock: true,
  },
  {
    id: "b2",
    name: "Solar Battery 200Ah",
    description: "Deep cycle battery ideal for solar storage",
    price: 1200000,
    category: "Batteries",
    condition: "Brand New",
    image: "/laptop-battery.png",
    images: ["/laptop-battery.png", "/placeholder.svg"],
    brand: "Generic",
    inStock: true,
  },
  // Power Stations
  {
    id: "ps1",
    name: "Portable Power Station 500W",
    description: "Backup power for camping and emergencies",
    price: 1800000,
    category: "Power Stations",
    condition: "Brand New",
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg"],
    brand: "EcoMax",
    inStock: true,
  },
  // Power Banks
  {
    id: "pb1",
    name: "20,000mAh Power Bank",
    description: "Fast charging PD power bank",
    price: 120000,
    category: "Power Banks",
    condition: "Brand New",
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg"],
    brand: "Anker",
    inStock: true,
  },
  // Lighting
  {
    id: "l1",
    name: "LED Floodlight 100W",
    description: "Bright outdoor lighting solution",
    price: 220000,
    category: "Lighting",
    condition: "Brand New",
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg"],
    brand: "BrightLite",
    inStock: true,
  },
  // Accessories
  {
    id: "a1",
    name: "Universal Travel Adapter",
    description: "Multi-country plug adapter",
    price: 45000,
    category: "Accessories",
    condition: "Brand New",
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg"],
    brand: "TravelPro",
    inStock: true,
  },
  // UPS Batteries
  {
    id: "u1",
    name: "UPS Battery 9Ah",
    description: "Replacement battery for UPS units",
    price: 85000,
    category: "UPS Batteries",
    condition: "Brand New",
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg"],
    brand: "APC",
    inStock: true,
  },
  // Cables & Adapters
  {
    id: "c1",
    name: "USB-C to Lightning Cable",
    description: "1m durable charging cable",
    price: 35000,
    category: "Cables & Adapters",
    condition: "Brand New",
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg"],
    brand: "Apple",
    inStock: true,
  },
]
